# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-14 04:27
from __future__ import unicode_literals

import arcutils.path
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
        ('web', '0002_auto_20171014_0606'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.QuestionChoice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ReadingQuestion')),
            ],
            options={
                'db_table': 'report_detail',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_new', models.BooleanField(default=True)),
                ('rank', models.IntegerField(default=0)),
                ('teacher', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='has_students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_profile',
            },
        ),
        migrations.CreateModel(
            name='StudentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'student_report',
            },
        ),
        migrations.AddField(
            model_name='readingmaterial',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='readingmaterial',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='readingfile',
            name='path',
            field=models.FileField(upload_to=arcutils.path.UploadToPathAndRename('files/2018/02')),
        ),
        migrations.AddField(
            model_name='studentreport',
            name='reading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ReadingMaterial'),
        ),
        migrations.AddField(
            model_name='studentreport',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportdetail',
            name='student_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.StudentReport'),
        ),
    ]
