# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-01 23:05
from __future__ import unicode_literals

import arcutils.path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20180214_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='avatar',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='readingfile',
            name='path',
            field=models.FileField(upload_to=arcutils.path.UploadToPathAndRename('files/2018/04')),
        ),
    ]
