# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-24 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_classroom_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='change_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='change_password',
            field=models.BooleanField(default=True),
        ),
    ]
