# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-11 10:07
from __future__ import unicode_literals

import arcutils.path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20180424_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingfile',
            name='path',
            field=models.FileField(upload_to=arcutils.path.UploadToPathAndRename('files/2019/07')),
        ),
    ]
