# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-31 10:42
from __future__ import unicode_literals

import arcutils.path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20190711_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingquestion',
            name='tutorial_file',
            field=models.FileField(blank=True, null=True, upload_to=arcutils.path.UploadToPathAndRename('tutorial/2019/07')),
        ),
    ]
