# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-08-23 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20190816_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='final_test_state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('state', models.BooleanField()),
            ],
            options={
                'db_table': 'final_test_state',
            },
        ),
        migrations.CreateModel(
            name='grade_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('text', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'grade_info',
            },
        ),
    ]
